argocd:
  namespace: argocd
  project: default

jenkins:
  repoURL: https://charts.jenkins.io
  chart: jenkins
  chartVersion: 5.9.18
  releaseName: jenkins

destination:
  server: https://kubernetes.default.svc
  namespace: jenkins

syncPolicy:
  prune: true
  selfHeal: true

library:
  name: jenkins-shared-library
  defaultVersion: main
  implicit: true
  repoURL: https://github.com/radubaltag-mtd/jenkins-shared-library.git
  credentialsId: shared-library-pat
