apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{ include "apache-stack.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Values.config.indexHtml | nindent 4 }}
