apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache
  labels:
    {{ include "apache-stack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{ include "apache-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "apache-stack.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: apache
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: apache-config
              mountPath: /var/www/html/index.html
              subPath: index.html
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: apache-config
          configMap:
            name: {{ .Release.Name }}-config
